### PR TITLE
[WIP] Issue 281: Add placeholder 404.html to app/templates

### PR DESCRIPTION
**Pull request by tekd**

### CODE REVIEW

**Comment by toolness** [comment]
Hey Denny! Sorry about the totally unhelpful 500 errors in the tests--we recently [switched testing frameworks](https://github.com/GovLab/noi2/pull/278) and one of the downsides is that the new one isn't showing the traceback of 500 errors that occur in tests. Lemme fix that real quick.

**Comment by toolness** [comment]
Ok, I just committed f307e2cae7a3cea22fdd0c71d088268cf0200f2e to the `master` branch, which should give you much better error feedback in tests!

**Comment by toolness** [comment]
Urgg, sorry the 500 errors still have no tracebacks on this one--recognized my folly and fixed it in ff96154d5e2054a0118a07856ed74b53817f405f. :disappointed:

**Comment by tekd** [comment]
No worries--they were only the source of a little panic! I finally got all of  the tests to pass though! I created a a separate error pages component with the blueprint error handler.

**Comment by toolness** [comment]
Err, something went weird with the merging, so I've simplified this PR into #295 and will close this one. Thanks @tekd!

**Pull request closed without merging**
