### PR TITLE
add tutorial step to User and associated JS

### PR DESCRIPTION
**Pull request by talos**

### CODE REVIEW

**Comment by toolness** [comment]
Ah that's cool, looks good to me!!

**Comment by toolness** [comment]
Actually while you are at it, do you want to add a `{% block page_script %}{% endblock %}` to that template as well?

**Comment by toolness** [comment]
Then we could actually re-base my `alert` and `user-menu` style guide pages to be based on `base.html` rather than the production base HTML...

**Comment by talos** [comment]
I'm confused -- I think there already is a `page_script` block on that `base.html`:

https://github.com/GovLab/noi2/blob/master/app/templates/__base__.html#L87

**Comment by toolness** [comment]
Oh, heh, I didn't see the existing `page_script` block. Carry on!

**Comment by toolness** [comment]
This looks good to me!

**Pull request merged**
