### PR TITLE
Implement new expertise UI.

### PR DESCRIPTION
**Pull request by toolness**
A lot of this code has been copied/pasted from existing code in registration step 3, since the two UIs are so similar; however, I'm leaving things un-refactored since we're not sure how much we'll want the two interfaces to deviate from one another in the very near future.

At least I was also able to copy/paste most of the unit tests from registration step 3, too!

### CODE REVIEW

**Comment by talos** [comment]
This looks good to merge, except that clicking on "next", "skip", an answer, or the "expertise" button should launch the user to the bottom of the expertise page.

**Comment by toolness** [comment]
O good point, I think I just fixed that.

**Comment by toolness** [comment]
I went ahead and added the fix for #131 to this PR because it involves factoring out a macro for `mailto:`/`data-connect-to` links, which touches the "E-mail" button in this code, so it was easiest to just add it to this  PR... Hope that's not too annoying.

**Comment by talos** [comment]
Nice! I'm going to merge this, but there's a basic disconnect between how we posed questions before and how we're doing them now.  See the mockup here:

https://trello.com/c/2y7dBq7k/14-my-profile-expertise-questions

Unfortunately, we didn't phrase stuff before quite as a question, there was some boilerplate around it.  In particular, there was a prepending with "I KNOW", then the phrase, then "AND" the option.

old-noi

I don't think the slide in Trello makes a lot of sense, and all our questions are set up to have that boilerplate, so this also doesn't make sense:

new-noi

I'm going to talk to Batu about reimagining these to make sense with our current vocab.

**Pull request merged**
