### PR TITLE
Rudimentary reskin of about page to new UI

### PR DESCRIPTION
**Pull request by toolness**
This just puts the About page in the new UI styling; it doesn't actually make it look particularly attractive, since we don't have HTML mocks for the about page yet. But it's way better than sending users to the About page with the old look-and-feel.

I also refactored the i18n a bit so that the `mailto:` link is an interpolated variable in the gettext string. This allows us to change the email and/or styling of that link without forcing localizers to re-translate the string.

Because we don't have a mockup for what the base UI should look like when the user is logged-out, I've taken the liberty of attempting to implement something:

The "i" on the topmost nav takes the user to the About page, while the user account circle takes the user to the login page (neither activates a modal/pop-up). Selecting any of the lower nav items takes the user to the login page too, though the user will be redirected to the appropriate place once they're logged in.

### CODE REVIEW

**Comment by toolness** [comment]
Er, shoot, because the About page doesn't require login/full registration and the `__base_ui__.html` template assumes that a user is logged in, things look weird if nobody's currently logged in. We might want to figure out what public pages like this look like...

**Comment by talos** [comment]
Yeah, that's a major issue since even the Activity page is supposed to be visible to non-logged in users.

**Comment by toolness** [comment]
Ok, I had some difficulty communicating the exact concern to batu and claudio so I just went ahead and quickly implemented something basic, so that they can see what the issue is and provide feedback. I updated this issue's description to reflect the change.

**Comment by talos** [comment]
This looks good to merge for now.  We still need to change things so that the Activity stream is visible to non-logged in users.

**Pull request merged**
