### PR TITLE
Make flask-security internationalize properly w/ interpolated strings.

### LINKED ISSUE #41: Registering with an already-registered email causes a traceback
Arg, internationalizing flask-security strikes again!!

Here's the traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_security/decorators.py", line 205, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_security/views.py", line 116, in register
    if form.validate_on_submit():
  File "/usr/local/lib/python2.7/dist-packages/flask_wtf/form.py", line 166, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/usr/local/lib/python2.7/dist-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/usr/local/lib/python2.7/dist-packages/wtforms/fields/core.py", line 200, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/fields/core.py", line 220, in _run_validation_chain
    validator(form, self)
  File "/usr/local/lib/python2.7/dist-packages/flask_security/forms.py", line 79, in unique_user_email
    msg = get_message('EMAIL_ALREADY_ASSOCIATED', email=field.data)[0]
  File "/usr/local/lib/python2.7/dist-packages/flask_security/utils.py", line 268, in get_message
    return rv[0] % kwargs, rv[1]
  File "/usr/local/lib/python2.7/dist-packages/speaklater.py", line 145, in __mod__
    return self.value % other
  File "/usr/local/lib/python2.7/dist-packages/speaklater.py", line 115, in <lambda>
    value = property(lambda x: x._func(*x._args, **x._kwargs))
  File "/usr/local/lib/python2.7/dist-packages/flask_babel/__init__.py", line 461, in gettext
    return t.ugettext(string) % variables
KeyError: u'email'
```

If I comment out our custom `lazy_gettext`'ed setting for `app.config['SECURITY_MSG_EMAIL_ALREADY_ASSOCIATED']` in `app/factory.py`, this traceback goes away, and the text "[email] is already associated with an account." appears as expected. So I'm guessing this was introduced by 0d52d9ae1bdc9b20acdd2c089b9c9a8a76d96492.

I suspect that the same problem might happen with `SECURITY_MSG_CONFIRM_REGISTRATION`, since it uses `%(email)s` in its gettext message too, but I haven't checked.

### PR DESCRIPTION
**Pull request by toolness**
This fixes #41.

### CODE REVIEW

**Comment by toolness** [comment]
Er, hold on, I think I might actually be able to fix this in a slightly less horrible way...

**Comment by toolness** [comment]
Ok, this fix consists of a bit more code, but is a lot cleaner IMO.

**Comment by talos** [comment]
Engage.

**Comment by toolness** [comment]
:grin:

**Pull request merged**
